USE PARTS;

SELECT DISTINCT 
J.J_ID, J.JNAME, J.CITY
FROM 
PROJECT J
WHERE CITY = 'LONDON';

CREATE TABLE CUSTOMERS
(CUSTOMER_ID INTEGER PRIMARY KEY,
NAME VARCHAR(50),
SURNAME VARCHAR(50) NOT NULL,
TELEPHONE INTEGER);
